version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecret123
      MYSQL_DATABASE: minitwitter
      MYSQL_USER: minitwitter
      MYSQL_PASSWORD: supersecret123
    volumes:
      - m223_project_mariadb:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - 9200:80

  backend:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules  # verhindert Nutzung der lokalen node_modules
    command: >
      sh -c "cd server &&
             npm install &&
             npm run build &&
             NODE_ENV=production npm start"
    ports:
      - 3000:3000
    depends_on:
      - mariadb


  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./client:/app
    command: >
      sh -c "npm install &&
             npm start"
    ports:
      - 4200:4200
    depends_on:
      - backend

volumes:
  m223_project_mariadb:
